"""Add credit packages table

Revision ID: fdbbdee419e0
Revises: a9cdaa0e2e9a
Create Date: 2026-08-04 19:24:30.012184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbbdee419e0'
down_revision: Union[str, None] = 'a9cdaa0e2e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_credit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    
    credit_packages = sa.table(
        'credit_packages',
        sa.column('id', sa.String),
        sa.column('name', sa.String),
        sa.column('credits', sa.Integer),
        sa.column('price', sa.Numeric),
        sa.column('price_per_credit', sa.Numeric),
        sa.column('is_active', sa.Boolean)
    )
    op.bulk_insert(
        credit_packages,
        [
            {'id': 'basico', 'name': 'Básico', 'credits': 10, 'price': 49.00, 'price_per_credit': 4.90, 'is_active': True},
            {'id': 'estandar', 'name': 'Estándar', 'credits': 30, 'price': 99.00, 'price_per_credit': 3.30, 'is_active': True},
            {'id': 'pro', 'name': 'Pro', 'credits': 100, 'price': 249.00, 'price_per_credit': 2.49, 'is_active': True}
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
